### DISCUSSION TITLE
Add fit to graphql

### DISCUSSION THREAD

**Discussion by bobevsky** [spatie/statamic-responsive-images#194] [Ideas]
When using the "Responsive" field in Statamic, you can pick between different options for FIT for the image.
But, when you use the "Assets" field and just use the "responsive" graphql query, there is no option for the FIT to be selected.
 
<img width="879" alt="Screenshot 2023-01-13 at 12 27 53" src="https://user-images.githubusercontent.com/44194428/212312650-c76a7739-5edf-47c9-ac7a-582009c0bd39.png">

Can we make an option to include this? We really love the focal-crops that you provide and it's a shame that we have to define "Responsive" field with no breakpoints and define the ratio all the time just to use the FIT.

<img width="793" alt="image" src="https://user-images.githubusercontent.com/44194428/212312119-fb218a39-df4b-40a9-9703-d3ca68c26859.png">

If it's possible, can you let us know how to always set the focal-crop to FIT?

**Comment by ncla** [comment]
Yeah at the moment there is a limited amount of parameters you can set through GraphQL. It is definitely lacking.

>it's a shame that we have to define "Responsive" field with no breakpoints and define the ratio all the time just to use the FIT.

As a workaround, continue using Responsive fieldtype, you can set default values in the blueprint to avoid filling out ratio and fit all the time. Like so in your blueprint yaml file:

```yaml
      -
        handle: responsive_field
        field:
          use_breakpoints: false
          allow_ratio: true
          allow_fit: false
          restrict: false
          allow_uploads: true
          display: 'Responsive Field'
          type: responsive
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
          default:
            ratio: '1234'
            'glide:fit': crop_focal
```
