### ISSUE TITLE
Duplicate `alt` attributes on generated images

### ISSUE THREAD

**Issue by sjclark** [spatie/statamic-responsive-images#104]
Having the majority of my images output with multiple alt tags on the front end; example below:

<img width="1168" alt="Screen Shot 2021-12-27 at 9 19 48 pm" src="https://user-images.githubusercontent.com/4531017/147463206-979c8726-b3a1-4a5b-bed1-8a4e3fa9d04e.png">

```html
...
    <img
        alt="Student group smiling in group while studying at table" fit="crop_focal" class="absolute inset-0 object-cover object-center w-full h-full"
        src="/assets/header-images/shutterstock_508251865.jpg"
        alt="shutterstock_508251865.jpg"
         width="4724"          height="3149"                 onload="
            this.onload=null;
            window.responsiveResizeObserver.observe(this);
        "
            >
</picture>
```

```html
{{ if header_image }}
{{ responsive:header_image glide:width="1000" glide:height="1000"
 alt="{header_image:alt}" fit="crop_focal"
 class="absolute inset-0 object-cover object-center w-full h-full"}}
{{ else }}
```
            
```yaml
data:
  focus: 59-47-1
  alt: 'Student group smiling in group while studying at table'
size: 8094941
last_modified: 1639972190
width: 4724
height: 3149
mime_type: image/jpeg

```

```yaml
subheading: 'Helping Domestic Learners & Providers Resolve Disputes'
header_image: header-images/shutterstock_508251865.jpg
```

```
Statamic 3.2.26 Pro
Laravel 8.75.0
PHP 8.0.13
aryehraber/statamic-captcha 1.7.0
spatie/statamic-responsive-images 2.8.5
```
