### ISSUE TITLE
Image in replicator set storage problems

### ISSUE THREAD

**Issue by hgrimelid** [spatie/statamic-responsive-images#118]
- statamic/cms 3.3.5
- spatie/statamic-responsive-images v. 2.11.0

I have created a replicator field with a responsive image field inside a set. 

When I create a second set with a new responsive image, the new image is added in the second set and the image in the first set is replaced with the image in the new set. 

When I save the entry, the image in the second set is removed, and the first image is replaced with that of the second (latest) set. 

`resources/fieldsets/responsive_image.yaml`:
```yaml
title: 'Responsive image'
fields:
  -
    handle: image
    field:
      use_breakpoints: true
      allow_ratio: false
      allow_fit: false
      breakpoints:
        - 2xl
      container: assets
      restrict: false
      allow_uploads: true
      display: Image
      type: responsive
      icon: assets
      listable: false
      instructions_position: above
      read_only: false

```

`resources/blueprints/collections/pages/pages.yaml`:
```yaml
title: Pages
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: replicator_field
        field:
          collapse: false
          sets:
            new_set:
              display: 'New Set'
              fields:
                -
                  import: responsive_image
                  prefix: unique_
          display: 'Replicator Field'
          type: replicator
          icon: replicator
          listable: false
          instructions_position: above
          read_only: false
  sidebar:
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
      -
        handle: parent
        field:
          type: entries
          collections:
            - pages
          max_items: 1
          listable: false
          localizable: true
```
