### ISSUE TITLE
Problem with Dirty State?

### ISSUE THREAD

**Issue by intrepidws** [spatie/statamic-responsive-images#120]
As part of upgrading to Statamic 3.3, I also upgraded from v2.9.3 of this package to v2.11.0. I am running into an issue that I believe traces back to usage of the responsive fieldtype made available by this package.

There are two issues occurring:
- When I make a responsive fieldtype required, it doesn't actually get required
- When I do select an image for the responsive fieldtype, and then try to save the collection item, I get a browser notification similar to what I would get if I were leaving the page before saving. See the below screenshot.

<img width="1251" alt="Screen Shot 2022-04-14 at 1 26 28 PM" src="https://user-images.githubusercontent.com/125735/163441836-7d8024c9-0516-422a-a04a-862bf51efd66.png">

I am running PHP 8.1, Laravel 8.83.8, Statamic 3.3.6 and Statamic Responsive Images 2.11.0.

Author Collection Blueprint YAML
```
title: Authors
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
          display: Name
          listable: true
          input_type: text
          antlers: false
      -
        handle: job_title
        field:
          input_type: text
          antlers: false
          display: 'Job Title'
          type: text
          icon: text
          listable: true
      -
        handle: header_photo
        field:
          use_breakpoints: false
          allow_ratio: false
          allow_fit: true
          breakpoints:
            - sm
            - md
            - lg
            - xl
            - 2xl
          container: assets
          folder: headers
          restrict: false
          allow_uploads: true
          display: Photo
          type: responsive
          icon: assets
          listable: hidden
          instructions_position: above
          read_only: false
          validate:
            - required
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
          validate:
            - required
          listable: hidden
          generate: true
```
