### ISSUE TITLE
Uncaught SyntaxError: 60

### ISSUE THREAD

**Issue by qbixx** [spatie/statamic-responsive-images#175]
### Bug description

When compiling the assets for production with `npm run production` the page doesn't load and only a white screen is visible. This probably is because of an issue in combination with Vue3.

When looking at the console log, I get the following error:

![Uploading Screenshot 2022-10-24 at 17.22.25.png…]()

### How to reproduce

I'm using the following packages:

TailwindCSS: 3.0.19
Vue: 3.2.31

When running `npm run watch` or `npm run develop` everythings works fine. However when running `npm run production` the error appears.

### Environment

```yaml
Application Name: Statamic
Laravel Version: 9.36.4
PHP Version: 8.0.20
Composer Version: 2.1.6
Environment: local
Debug Mode: ENABLED
URL: 
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: regex
Version: 3.3.48 PRO

Statamic Addons
edalzell/forma: 1.2
silentz/mailchimp: 2.9.1
spatie/statamic-responsive-images: 2.14.2
statamic/seo-pro: 3.1.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
