### ISSUE TITLE
GraphQL Images producing too much data

### ISSUE THREAD

**Issue by bobevsky** [spatie/statamic-responsive-images#188]
### Bug description

I tested out the GraphQL plugin and found out that the srcSetWebp / srcSet / placeholder are producing way too much data.

Consider these scenarios:

1. I am getting the srcSetWebp and also placeholder. If i get both of those, the page data for my page is 370kb. (huge)
2. If i get the srcSetWebp only and remove the placeholders, the page data is 244kb (126kb just for placeholders that are appearing like for a split second while the image is loading)
3. If i remove both srcSetWebp and also placeholder my page data is 56kb (ridiculous how much data these images produce) and how much they slow the pages.

Now, all of my projects are with headless CMS and Nextjs and for them to be loaded with images it's extremely slow sometimes.

All of that data is because the long characters that srcSetWebp / srcSet / placeholder are generating. What can we do about that?

### How to reproduce

Just execute 1 graphQL query on any image using the srcSetWebp / srcSet / placeholder and you will get extremely long strings which produce way too much data.

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.43.0
PHP Version: 8.1.13
Composer Version: 2.4.4

Statamic
Addons: 12
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.61 PRO
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
