### ISSUE TITLE
Sources not being generated for image in 3.0+

### ISSUE THREAD

**Issue by taylorcammack** [spatie/statamic-responsive-images#205]
### Bug description

Passing in an image from an asset fieldtype, sources no longer being generated as of 3.0+. This works in latest 2.0 version.

- I made sure to replace the `responsive-images.php` files in config after going to 3.0 (I have some custom breakpoints), but even tossing my minor customization and going with default config, still seeing this.
- Also removed the breakpoints and went with just the tag: `{{ responsive:hero_image }}`. No difference.

Is there something I missed in the Upgrade guide? Note that I **can't** replicate this on a fresh Statamic install, so must be something wonky with my project.

```
  {{ if hero_image }}
    <figure>
      {{ responsive:hero_image ratio="1.5" md:ratio="2.2" lg:ratio="2.85" xl:ratio="3" 2xl:ratio="4" glide:width="2000" }}
    </figure>
  {{ /if }}
```

![Screenshot 2023-02-09 at 10 23 08 AM](https://user-images.githubusercontent.com/2514935/217873453-608c8416-dd77-41fc-947c-d1f2b42a9662.jpg)

### How to reproduce

- create an asset fieldtype
- attempt to display image 

### Environment

```yaml
Environment
Laravel Version: 9.51.0
PHP Version: 8.1.11
Composer Version: 2.5-dev+50cded331ced9acb4e926be3dda1f74b86af2a3b
Environment: local
Debug Mode: ENABLED
Maintenance Mode: OFF

Cache
Config: CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 9
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.3 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.9.1
encore/encore: dev-main
goldnead/statamic-collapse-fieldtype: 1.0.4
jonassiewertsen/statamic-livewire: 2.11.0
mitydigital/iconamic: 1.1.2
rias/statamic-data-import: 1.2.2
simonhamp/statamic-heroicons: 1.1.0
spatie/statamic-responsive-images: 3.1.0
webographen/statamic-dynamic-token: 1.0.0
```

### Installation

Other (please explain)

### Antlers Parser

runtime (new)
