### ISSUE TITLE
GraphQL error Undefined array key "src"

### ISSUE THREAD

**Issue by k-aleksandar** [spatie/statamic-responsive-images#214]
### Bug description

If you have a simple collection where you have a Responsive field type with validation not required, then you need some entries where in some of them the Responsive filed type is empty. 

Then in the entries query in GraphQL if you select data from the Responsive field when executing the query you will get an error with debug message  "Undefined array key 'src'".

The root of the error is src/GraphQL/ResponsiveFieldType.php file, and if you add this line of code
if (!isset($field['src'])) return [];
in the file on line 39 the error is fixed.

### How to reproduce

GraphQL query example

query MyQuery {
  entries(collection: "products") {
    data {
        ... on Entry_Products_Products {
          id
          overview_image {
            breakpoints {
              label
              ratio
            }
          }
        }
      }
  }
}

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.5
PHP Version: 8.1.12
Composer Version: 2.5.1
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.1 PRO

Statamic Addons
spatie/statamic-responsive-images: 3.1.3
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

**Comment by ncla** [comment]
I am unable to reproduce this issue.

I have two entries in a collection, one has default breakpoint image selected, one does not. So the content .md files look like this:

```yaml
---
id: home
blueprint: pages
title: Home
template: home
author: c8b68d28-46af-4be7-bc4b-9147453f5fc0
updated_by: c8b68d28-46af-4be7-bc4b-9147453f5fc0
updated_at: 1676145264
responsive_field:
  src: poster.jpg
---
```

and 

```yaml
---
id: 7314f75e-acbc-48b2-aefa-782a8de3b681
blueprint: pages
title: 'Another one'
updated_by: c8b68d28-46af-4be7-bc4b-9147453f5fc0
updated_at: 1680871290
---
```

Pages blueprint responsive fieldtype configured like so:

```yaml
      -
        handle: responsive_field
        field:
          use_breakpoints: true
          allow_ratio: true
          allow_fit: true
          restrict: false
          allow_uploads: true
          display: 'Responsive Field'
          type: responsive
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
          breakpoints:
            - lg
```

GraphQL query I am running on http://localhost/cp/graphiql and the output

![image](https://user-images.githubusercontent.com/5507083/230611488-a0fd98c4-9851-4c36-9992-1bf40b5489e0.png)

Only difference with your query is that you have `query MyQuery` added at the start, which I do not.

Works for me as expected. 

If we are talking about error logs in your log files, then that seems correct according to the code, there is a very generous `try .. catch` statement in `ResponsiveFieldtype`, which logs any errors.

Here's the next steps for you:

1. Is this error appearing in the request output or in `laravel.log`?
2. Can you please provide your minimal blueprint and content files?
3. Please provide full error stack trace.

Any additional information would be great too.
