### ISSUE TITLE
Unlisted Addon

### ISSUE THREAD

**Issue by imbwaldo** [spatie/statamic-responsive-images#236]
### Bug description

After updating to Statamic 4.18.0, Responsive Images now appears in the "Unlisted Addons" section of the Updates tab:

<img width="526" alt="Screenshot 2023-08-22 at 1 12 41 PM" src="https://github.com/spatie/statamic-responsive-images/assets/1582379/114b444e-34a8-4367-9298-aaae79983cca">

Seems like the addon is still working, but I'm not sure what its unregistered status means. Is there something I need to do to correct it?

### How to reproduce

Not sure …

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 9.52.15
PHP Version: 8.1.22
Composer Version: 2.5.8
Environment: local
Debug Mode: OFF
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.18.0 PRO

Statamic Addons
aryehraber/statamic-logbook: 3.1.0
mitydigital/feedamic: 2.2.6
rias/statamic-redirect: 3.1.0
spatie/statamic-responsive-images: 4.1.1
statamic/seo-pro: 5.2.2
visuellverstehen/statamic-classify: 2.6.1
```

### Installation

Existing Laravel app

### Antlers Parser

regex (default)
