### ISSUE TITLE
Fields with errors not being highlighted after the Responsive field

### ISSUE THREAD

**Issue by RyanEvoluted** [spatie/statamic-responsive-images#237]
### Bug description

When using the Responsive field, all highlighted fields after the section it's in don't seem to appear.

Example:

Section 1:
Responsive Field

Section 2:
Title

If the Title field is required and submitted without any input, the Title field isn't highlighted with a red border.

<img width="80%" alt="Screenshot 2023-09-06 at 16 25 29" src="https://github.com/spatie/statamic-responsive-images/assets/144149497/4fca6e21-6592-48f8-9563-6f6f44d50ee3">

When Section 2 is moved above Section 1. The Title will be highlighted as normal if no data is supplied.

<img width="80%" alt="Screenshot 2023-09-07 at 10 23 09" src="https://github.com/spatie/statamic-responsive-images/assets/144149497/9f98addd-538a-4d28-8085-fd9ee41d802a">

I'm expecting all the required fields to be highlighted in a red border rather than the ones that are in the same section as the responsive field or before it.

### How to reproduce

1. In a blueprint, add a 'Responsive' field to the first section
   - Make sure there's a required field in the section after it
2. Try and create an entry for the blueprint you've edited. You should notice the required field won't be highlighted in a red border
3. Back in the blueprint, drag the section with the 'Responsive' field after a section which has a required field
4. Create an entry again and you should find that the requried field will be highlighted

### Environment

```yaml
Environment
Application Name: Statamic
Laravel Version: 10.22.0
PHP Version: 8.1.15
Composer Version: 2.3.5
Environment: local
Debug Mode: ENABLED
URL: ryan_test.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.20.0 Solo

Statamic Addons
spatie/statamic-responsive-images: 4.1.1
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)

### Additional details

This is happening on another established project but I was able to replicate this on a fresh install of Statamic.
