### ISSUE TITLE
Incorrect width/height when switching aspect ratios

### ISSUE THREAD

**Issue by jimblue** [spatie/statamic-responsive-images#257]
### Bug description

Currently, the plugin calculates width/height incorrectly when swapping aspect ratios, leading to incorrect HTML output.
When changing the aspect ratio of an image, the longest side should remain fixed, and the other side should be calculated accordingly.

### How to reproduce

For an image of 3000x1688px as a source:

```twig
{{ responsive:image ratio="16/9" md:ratio="9/16" }}
```
it returns:

```html
<picture>
    <source [...] >
    <source [...] >
    <source [...] >
    <img src="/img/asset/hash/image.jpg?w=3000&amp;h=1688&amp;s=9358bb54be5d388a9a2529a4196dcfc6" alt="" width="3000" height="1688">
</picture>
```

Now for the same image as source but with:

```twig
{{ responsive:image ratio="9/16" md:ratio="16/9" }}
```
it returns:

```html
<picture>
    <source [...] >
    <source [...] >
    <source [...] >
    <img src="/img/asset/hash/image.jpg?w=3000&amp;h=5333&amp;s=6c5c0bb8447dbd7ff61a692f98b5f46d" alt="" width="3000" height="5333">
</picture>
```

### Logs

```shell

```

### Environment

```yaml
Environment
Application Name: local
Laravel Version: 11.41.3
PHP Version: 8.3.14
Composer Version: 2.8.5
Environment: development
Debug Mode: ENABLED
URL: local.test
Maintenance Mode: OFF
Timezone: Europe/Paris
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: redis
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Disabled (auto)
Static Caching: Disabled
Version: 5.46.0 PRO

Statamic Addons
rias/statamic-redirect: 3.9.3
spatie/statamic-responsive-images: 5.2.1
statamic/seo-pro: 6.5.0
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
