### ISSUE TITLE
Unable to add a custom breakpoint to the config file

### ISSUE THREAD

**Issue by ELowry** [spatie/statamic-responsive-images#260]
### Bug description

I added a custom breakpoint to the `responsive-images.php` config file, but it does not show up in the control panel (either when modifying a blueprint/fieldset; or when editing an entry).

### How to reproduce

1. I published `responsive-images.php` to `/config/` (though I also tried this from within the `vendor` folder just in case).
2. I added a custom breakpoint:

```php
	'breakpoints' => [
		'logo' => 128,
		'sm' => 640,
		'md' => 768,
		'lg' => 1024,
		'xl' => 1280,
		'2xl' => 1536,
	],
```
3. Run the following commands

```sh
php artisan config:clear
php artisan cache:clear
php please cache:clear
```

### Environment

```yaml
Environment
Application Name: CinQ Leadership & Teamwork Lab
Laravel Version: 11.44.1
PHP Version: 8.3.19
Composer Version: 2.8.6
Environment: local
Debug Mode: ENABLED
URL: cinq.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: gmail
Queue: sync
Session: file

Statamic
Addons: 5
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.50.0 Solo

Statamic Addons
rias/statamic-collection-groups: 1.1.0
spatie/statamic-responsive-images: 5.2.2
studio1902/statamic-peak-browser-appearance: 3.6.1
studio1902/statamic-peak-seo: 8.19.1
studio1902/statamic-peak-tools: 7.1.0
```

### Installation

Starter Kit using via CLI

### Antlers Parser

runtime (new)
