### ISSUE TITLE
Incorrect alt tag

### ISSUE THREAD

**Issue by strixTheCaptn** [spatie/statamic-responsive-images#262]
### Bug description

When adding different images for different breakpoints, the `<img>` tag always loads the same alt tag, no matter which image is shown.

The bug is happening in `responsiveImage.blade.php` where the `$asset` variable does not match the actual image on line 42. #

### How to reproduce

* Add images for different breakpoints. Give the images their own alt tag

### Logs

```shell

```

### Environment

```yaml
✔ ~/repo [:efa6b7a|✚ 1…2⚑ 1]
12:45 $ php please support:details

Environment
Application Name: Statamic
Laravel Version: 12.8.1
PHP Version: 8.4.7
Composer Version: 2.8.8
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: UTC
Locale: de

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Storage
public/storage: NOT LINKED

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.53.0 PRO

Statamic Addons
spatie/statamic-responsive-images: 5.2.2
``
```

### Installation

Fresh statamic/statamic site via CLI

### Antlers Parser

regex (default)
