### ISSUE TITLE
Passing a `null` ratio throws division by 0

### ISSUE THREAD

**Issue by xjoke** [spatie/statamic-responsive-images#41]
I have a fieldset for adding an image that also includes a textfield for a caption and the wanted ratio. This fieldset is used in Bards and on their own, the error occurs in both cases when the fieldset's ratio field is left empty. This has worked previously.

**Fieldset:**
```yaml
title: Image
fields:
  - handle: image
    field:
      max_files: 1
      display: Image
      type: assets
      [...]
  - handle: ratio
    field:
      placeholder: 'e.g. 16/9'
      input_type: text
      type: text
      validate:
        - 'regex:/^\d+(\.\d*)?\/\d+(\.\d*)?$/'
      [...]
  [...]
```

**Template:**
```
{{ responsive:image [...] :ratio='ratio' }}
```

**Error:**
```
Facade\Ignition\Exceptions\ViewException
Division by zero

at src/Breakpoint.php:139
```
