### ISSUE TITLE
retrieveAsset(): Return value must be of type Statamic\Assets\Asset, array returned

### ISSUE THREAD

**Issue by chrislcarr** [spatie/statamic-responsive-images#58]
After upgrading to the latest version (v2.5.0), I immediately encountered the following error:

**Facade\Ignition\Exceptions\ViewException
Spatie\ResponsiveImages\Responsive::retrieveAsset(): Return value must be of type Statamic\Assets\Asset, array returned**

I put a dump in the  `retrieveAsset($assetParam)` function within `Responsive.php`, right before `return $asset;` and got the following:
```
Statamic\Assets\Asset {#2480 ▼
  #container: Statamic\Assets\AssetContainer {#2572 ▼
    #title: "Assets"
    #handle: "assets"
    #disk: "assets"
    #private: null
    #allowUploads: null
    #allowDownloading: null
    #allowMoving: null
    #allowRenaming: null
    #createFolders: null
    #searchIndex: null
    #initialPath: null
  }
  #path: "backgrounds/bkgd_features-tablet.png"
  #meta: array:5 [▼
    "data" => array:1 [▼
      "focus" => "65-34-1"
    ]
    "size" => 1043221
    "last_modified" => 1612790746
    "width" => 1536
    "height" => 847
  ]
  #data: Illuminate\Support\Collection {#2633 ▼
    #items: array:1 [▼
      "focus" => "65-34-1"
    ]
  }
  #supplements: Illuminate\Support\Collection {#2667 ▼
    #items: []
  }
}
```

I was able to get back to a working version by making the following change in my `composer.json`:

- FROM: `"spatie/statamic-responsive-images": "^2.5"`
- TO: `"spatie/statamic-responsive-images": "2.4"`

**Comment by riasvdv** [comment]
Could you show me how you're using the responsive tag?

**Comment by martink635** [comment]
I have the same problem, just installed it on the latest Statamic v3.

The tag is simply used: `{{ responsive:bottom_image }}` and the yaml:
```
...
              handle: bottom_image
              field:
                use_breakpoints: false
                allow_ratio: true
                allow_fit: true
                container: assets
                restrict: false
                allow_uploads: true
                display: 'Bottom Image'
                type: responsive
                icon: assets
                listable: hidden
                validate:
                  - required
...
```
