### ISSUE TITLE
Responsive images in global returns array

### ISSUE THREAD

**Issue by BobWez98** [spatie/statamic-responsive-images#75]
I have configured a responsive field on a global. This returns a array instead of a `Statamic\Fields\Value` with type of `ResponsiveImage` and therefore the @responsive tag gives the error:
"Array to string conversion".

**Comment by riasvdv** [comment]
Could you share the relevant part of the global's `yaml` file so I can see how exactly it's set up?

**Comment by BobWez98** [comment]
Sure! I'm using [the blade directive @globalset from this package](https://github.com/edalzell/statamic-blade). It might be an issue with how they fetch the globals data i don't know. The yaml of the global is as follow's:
```yaml
sections:
  main:
    display: Main
    fields:
      -
        handle: company_name
        field:
          input_type: text
          antlers: false
          display: 'Company Naam'
          type: text
          icon: text
          listable: hidden
      -
        handle: logo
        field:
          use_breakpoints: true
          allow_ratio: true
          allow_fit: true
          breakpoints:
            - sm
            - md
            - lg
            - xl
            - 2xl
          container: assets
          restrict: false
          allow_uploads: true
          display: Logo
          type: responsive
          icon: assets
          listable: hidden

```
