### ISSUE TITLE
Upgrade to 2.8.3 (or 2.8.4) breaks responsive images

### ISSUE THREAD

**Issue by intrepidws** [spatie/statamic-responsive-images#99]
On Statamic 3.2.18, upgrading this package to either 2.8.3 or 2.8.4 prevents my responsive images from displaying. The output from the tag is nothing - no `<script>` tag and no `<picture>` tag at all.

The problem seems related to the change (made in 2.8.3) from using `value()` to instead using `raw()` in this line:

https://github.com/spatie/statamic-responsive-images/blob/a0189997aa49764293dc9bdcd5dd7ee53ecb3444/src/Responsive.php#L32

If I revert change that method from `raw()` back to `value()`, it fixes the problem.

I'm happy to submit a PR to fix this, but I don't have a full understanding of whether this is something that is broken for everyone - or just me. I figured I'd post this issue to see if perhaps it's me doing something wrong first.

This is the code used on my site to display the responsive image:

```
{{ responsive:header_photo class="w-full h-full object-cover" alt="{ title }" }}
```

And this is the field definition:

```
      -
        handle: header_photo
        field:
          use_breakpoints: false
          allow_ratio: false
          allow_fit: true
          breakpoints:
            - sm
            - md
            - lg
            - xl
            - 2xl
          container: assets
          folder: headers
          restrict: false
          allow_uploads: true
          display: Photo
          type: responsive
          icon: assets
          listable: hidden
          validate:
            - required
```
